---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: balancer
  become: yes
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: yes
  roles:
    - role: download
      rke2_chksum: "{{ lookup('url', 'https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/sha256sum-amd64.txt') }}"

- hosts: controller
  become: yes
  roles:
    - role: rke2/controller

- hosts: controller
  become: true
  roles:
    - role: rke2/cni
      when: 
        - ( cni_native == "none" and 
            cni_plugin != "none")

- hosts: worker
  become: yes
  roles:
    - role: rke2/worker

- hosts: controller
  become: true
  roles:
    - role: metallb 
      when: metallb_deploy == true
