---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: prereq

- hosts: balancer
  become: true
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: true
  roles:
    - role: download
      rke2_chksum: "{{ lookup('url', 'https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/sha256sum-amd64.txt') }}"

- hosts: controller
  become: true
  serial: 
    - 1
    - 2
  roles:
    - role: rke2/controller
      vars:
        k8s_version_split: "{{k8s_version.split('.')}}" 

- hosts: controller
  become: true
  roles:
    - role: rke2/cni
      when: 
        - ( cni_native == "none" and 
            cni_plugin != "none")      

- hosts: worker
  become: true
  roles:
    - role: rke2/worker
