---

- name: Copy rke2 service file
  template:
    src: "rke2.service.j2"
    dest: "{{ systemd_dir }}/rke2-agent.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and wait for rke2 service
  systemd:
    name: rke2-agent
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: service
  until: service.failed == false
  retries: 10
  delay: 15
