---
rke2_version: v1.26.3+rke2r1

# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "Your/Timezone"

# Set CNI native plugin choice none, canal, cilium or calico
cni_native: "canal"

# Set CNI external plugin choice none, flannel, canal, or calico
cni_plugin: "none"

# interface which will be used for flannel
cni_iface: "eth0"

# POD Subnet
# check cni documentation for the appropriate cidr
podsubnet: "10.244.0.0/16"

# apiserver_endpoint is virtual ip-address of the load balancer
apiserver_endpoint: "192.168.1.17"

# rke2_token is required so controllers can talk together securely
# this token should be alpha numeric only
rke2_token: "some-SUPER-DEDEUPER-secret-password"

# RKE2 initialization options, add or change these to your liking. 
extra_server_args: "--node-taint CriticalAddonsOnly=true:NoExecute --disable rke2-ingress-nginx"
extra_agent_args: " "

# Default Gateway
default_gateway:
  "192.168.1.1"

# Nameservers to use in resolv.conf.
dns_nameservers:
  - "9.9.9.9"
  - "1.1.1.1"

# NFS Client Configuration 
nfs_server: "192.168.1.10" 
nfs_path: "/srv/nfs/kubedata"

# DHCP address of unitilized bare-metal hosts
new_hosts:
  - 192.168.1.11
  - 192.168.1.12
  - 192.168.1.13
  - 192.168.1.14
  - 192.168.1.15
  - 192.168.1.16
  - 192.168.1.17

# Mapping of hardware MAC addresses should be configured with specific IPs and Hostnames
mac_address_mapping:
  "00:01:ff:33:d6:18":
    name: ctrl-01.example.local
    ip: "192.168.1.11"
  "00:01:ff:1a:e7:78":
    name: ctrl-02.example.local
    ip: "192.168.1.12"
  "00:01:ff:e0:9b:34":
    name: ctrl-03.example.local
    ip: "192.168.1.13"
  "00:01:ff:ca:72:3b":
    name: wrkr-01.example.local
    ip: "192.168.1.14"
  "00:01:ff:86:5c:c4":
    name: wrkr-02.example.local
    ip: "192.168.1.15"
  "00:01:ff:58:51:c2":
    name: wrkr-03.example.local
    ip: "192.168.1.16"
  "00:01:ff:78:78:d5":
    name: nginx-lb.example.local
    ip: "192.168.1.17"

# CNI Manifest URLs
# Calico Manifest url 
calico_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml"
calico_crd: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml"
# Flannel Manifest URL
flannel_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
# Canal Manifest URL 
canal_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/canal.yaml"