---
ansible_user: root
server_init_args: >-
  {% if groups['controller'] | length > 1 %} 
    {% if ansible_hostname == hostvars[groups['controller'][0]]['ansible_hostname'] %} 

    {% else %} 
      --server https://{{ apiserver_endpoint }}:9345 
    {% endif %} 
    --token {{ rke2_token }} 
  {% endif %} 
  {{ extra_server_args | default('') }}
