---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - rke2
    - rke2-agent

- name: Remove RKE2 binary file 
  ansible.builtin.file:
    path: /usr/local/bin/rke2
    state: absent

- name: Remove RKE2 tarball file 
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/images/rke2-images-core.linux-amd64.tar.gz
    state: absent

- name: Remove RKE2 Images directory 
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/images/
    state: directory
    state: absent

- name: pkill -9 -f "rke2/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "rke2/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount Rancher filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /run/netns
    - /var/lib/rancher/
  loop_control:
    loop_var: mounted_fs

- name: Remove RKE2 service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/rke2
    - /usr/local/bin/rke2-killall.sh
    - /usr/local/bin/rke2-uninstall.sh
    - "{{ systemd_dir }}/rke2.service"
    - "{{ systemd_dir }}/rke2-node.service"
    - /etc/rancher/rke2
    - /var/lib/rancher/
    - "/home/{{ ansible_user }}/.kube/config"
    - /opt/cni/bin
    - /etc/cni

- name: daemon_reload
  systemd:
    daemon_reload: yes

- name: Clean up cni interfaces
  shell: |
    sudo ip link delete cni0
    sudo ip link delete flannel.1
    sudo ip link delete flannel-v6.1
    sudo ip link delete flannel-wg
    sudo ip link delete vxlan.calico
    sudo ip link delete vxlan-v6.calico
    sudo ip link delete cilium_vxlan
    sudo ip link delete cilium_net
    sudo ip link delete kube-ipvs0
  failed_when: false
  ignore_errors: true

- name: Remove kubectl 
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
     packages:
     - kubectl  
